-- MySQL Script generated by MySQL Workbench
-- Ср 02 ноя 2016 13:50:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema nasa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nasa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nasa` DEFAULT CHARACTER SET utf8 ;
USE `nasa` ;

-- -----------------------------------------------------
-- Table `nasa`.`content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nasa`.`content` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `image_url` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nasa`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nasa`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `text` VARCHAR(45) NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `content_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_content_idx` (`content_id` ASC),
  CONSTRAINT `fk_comment_content`
    FOREIGN KEY (`content_id`)
    REFERENCES `nasa`.`content` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
